export const COMPANY = {
  name: 'True Commercial Service',
  legal: 'True Commercial Service LLC',
  phone: '(405) 555-8247',
  phoneHref: 'tel:+14055558247',
  emergencyPhone: '(405) 555-8248',
  emergencyPhoneHref: 'tel:+14055558248',
  email: 'service@choosetrue.com',
  tagline: 'Commercial Kitchen Equipment Repair. Done Right.',
  description: 'True Commercial Service is a tech-forward commercial kitchen equipment repair company serving Oklahoma City, Northern New Jersey, and Atlanta.',
};

export const SERVICES = [
  {
    slug: 'cooking-equipment',
    title: 'Cooking Equipment Repair',
    shortTitle: 'Cooking',
    icon: 'Flame',
    description: 'Ovens, ranges, fryers, griddles, steamers, and more. Factory-trained techs who fix it right the first time.',
    longDescription: 'From combi ovens to conveyor ovens, charbroilers to tilt skillets — we repair every major brand of commercial cooking equipment. Our technicians carry manufacturer certifications and the diagnostic tools to identify issues fast. No guesswork. No repeat visits.',
    equipment: ['Combi Ovens', 'Convection Ovens', 'Conveyor Ovens', 'Fryers', 'Griddles', 'Charbroilers', 'Ranges', 'Steamers', 'Tilt Skillets', 'Salamanders', 'Rotisseries', 'Induction Cooktops'],
    brands: ['Rational', 'Alto-Shaam', 'Vulcan', 'Garland', 'Blodgett', 'Henny Penny', 'Pitco', 'Frymaster', 'Cleveland', 'TurboChef'],
  },
  {
    slug: 'refrigeration',
    title: 'Commercial Refrigeration Repair',
    shortTitle: 'Refrigeration',
    icon: 'Thermometer',
    description: 'Walk-in coolers, reach-ins, prep tables, display cases. Fast response to protect your inventory.',
    longDescription: 'Refrigeration failures cost you money every minute. We prioritize refrigeration calls because your inventory is on the line. Walk-in coolers, reach-in units, prep tables, display merchandisers — we service them all with the urgency they demand.',
    equipment: ['Walk-In Coolers', 'Walk-In Freezers', 'Reach-In Refrigerators', 'Prep Tables', 'Display Cases', 'Ice Cream Cabinets', 'Blast Chillers', 'Undercounter Units', 'Refrigerated Bases'],
    brands: ['True Manufacturing', 'Traulsen', 'Hoshizaki', 'Turbo Air', 'Continental', 'Beverage-Air', 'Delfield', 'Randell', 'Master-Bilt'],
  },
  {
    slug: 'hvac',
    title: 'Commercial HVAC Service',
    shortTitle: 'HVAC',
    icon: 'Wind',
    description: 'Rooftop units, kitchen ventilation, makeup air. Keep your kitchen and dining room comfortable year-round.',
    longDescription: 'Commercial kitchens generate massive amounts of heat. Your HVAC system is working harder than anywhere else. We maintain and repair rooftop units, split systems, kitchen ventilation hoods, makeup air units, and exhaust fans — keeping your staff comfortable and your kitchen code-compliant.',
    equipment: ['Rooftop Units (RTUs)', 'Split Systems', 'Kitchen Exhaust Hoods', 'Makeup Air Units', 'Exhaust Fans', 'VRF Systems', 'Walk-In Unit Coolers', 'Condensing Units'],
    brands: ['Carrier', 'Trane', 'Lennox', 'Daikin', 'Bard', 'Captive Aire', 'Accurex'],
  },
  {
    slug: 'beverage-equipment',
    title: 'Beverage Equipment Repair',
    shortTitle: 'Beverage',
    icon: 'GlassWater',
    description: 'Ice machines, fountain dispensers, tea brewers, juice systems. Keep the drinks flowing.',
    longDescription: 'Nothing slows down service like a broken ice machine or a downed fountain system. We repair and maintain all major brands of commercial beverage equipment — from Hoshizaki and Manitowoc ice machines to Bunn brewers and fountain systems.',
    equipment: ['Ice Machines', 'Fountain Dispensers', 'Tea Brewers', 'Coffee Brewers', 'Juice Dispensers', 'Beer Systems', 'Water Filtration', 'Carbonation Systems'],
    brands: ['Hoshizaki', 'Manitowoc', 'Scotsman', 'Ice-O-Matic', 'Bunn', 'Cornelius', 'Lancer', 'Wunder-Bar'],
  },
  {
    slug: 'espresso-machines',
    title: 'Espresso Machine Repair',
    shortTitle: 'Espresso',
    icon: 'Coffee',
    description: 'Specialized service for commercial espresso machines. Multi-group, superautomatic, and grinders.',
    longDescription: 'Commercial espresso machines are precision instruments. Most service companies won\'t touch them. We will — and we\'ll fix them right. From PID tuning to group head rebuilds, boiler descaling to grinder calibration, our techs have deep training on the machines that matter to your coffee program.',
    equipment: ['Multi-Group Espresso Machines', 'Superautomatic Machines', 'Commercial Grinders', 'Steam Wands', 'Group Heads', 'Boilers', 'Water Treatment Systems'],
    brands: ['La Marzocco', 'Nuova Simonelli', 'La Cimbali', 'Rancilio', 'Slayer', 'Synesso', 'Mazzer', 'Mahlkönig'],
  },
  {
    slug: 'preventive-maintenance',
    title: 'Preventive Maintenance Agreements',
    shortTitle: 'PM Plans',
    icon: 'ShieldCheck',
    description: 'Scheduled maintenance that extends equipment life and prevents costly emergency calls.',
    longDescription: 'The smartest operators don\'t wait for breakdowns. Our Preventive Maintenance agreements put your equipment on a scheduled service cadence — cleaning, calibrating, and inspecting before small issues become expensive emergencies. We build custom PM plans based on your equipment inventory and usage patterns.',
    equipment: ['Full Kitchen PM Programs', 'Refrigeration-Only PM', 'HVAC PM', 'Custom Equipment Audits', 'Seasonal Tune-Ups'],
    brands: [],
  },
];

export const LOCATIONS = [
  // ─── OKC METRO ────────────────────────────────────────────────
  {
    slug: 'oklahoma-city',
    city: 'Oklahoma City',
    state: 'OK',
    status: 'active' as const,
    tagline: 'Serving the OKC Metro and Central Oklahoma',
    phone: '(405) 555-8247',
    phoneHref: 'tel:+14055558247',
    serviceArea: ['Oklahoma City', 'Norman', 'Edmond', 'Moore', 'Midwest City', 'Del City', 'Yukon', 'Mustang', 'Bethany', 'Stillwater', 'Shawnee'],
    description: 'True Commercial Service is Oklahoma City\'s premier commercial kitchen equipment repair provider. From Bricktown restaurants to campus dining at OU and OSU, we keep commercial kitchens running across Central Oklahoma.',
    seoTitle: 'Oklahoma City Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Expert commercial kitchen equipment repair in Oklahoma City. Cooking, refrigeration, HVAC, and espresso machine service for restaurants, schools, and institutions across the OKC metro.',
    seoKeyword: 'Oklahoma City commercial kitchen equipment repair',
  },
  {
    slug: 'norman-ok',
    city: 'Norman',
    state: 'OK',
    status: 'active' as const,
    tagline: 'Serving Norman, OU Campus & South OKC Metro',
    phone: '(405) 555-8247',
    phoneHref: 'tel:+14055558247',
    serviceArea: ['Norman', 'Moore', 'Noble', 'Purcell', 'Blanchard', 'Newcastle', 'Goldsby', 'Slaughterville', 'Lexington', 'South Oklahoma City'],
    description: 'True Commercial Service provides fast, expert commercial kitchen equipment repair in Norman, OK. We serve Campus Corner restaurants, Lindsey Street food spots, university dining at OU, and every commercial kitchen in the Norman metro. Same-day response, factory-trained techs, and AI-powered diagnostics.',
    seoTitle: 'Norman OK Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Norman OK. Fast response for restaurants, OU campus dining, and commercial kitchens. Refrigeration, cooking, HVAC, ice machines. 24/7 emergency service.',
    seoKeyword: 'Norman OK commercial kitchen equipment repair',
  },
  {
    slug: 'edmond-ok',
    city: 'Edmond',
    state: 'OK',
    status: 'active' as const,
    tagline: 'Serving Edmond, Deer Creek & North OKC Metro',
    phone: '(405) 555-8247',
    phoneHref: 'tel:+14055558247',
    serviceArea: ['Edmond', 'Deer Creek', 'Arcadia', 'Guthrie', 'North Oklahoma City', 'The Village', 'Nichols Hills', 'Warr Acres', 'Bethany', 'Piedmont'],
    description: 'True Commercial Service is Edmond\'s go-to commercial kitchen equipment repair company. From the UCO campus to the booming restaurant scene along Broadway and 2nd Street, we deliver fast, expert equipment repair with AI-powered diagnostics and same-day emergency response.',
    seoTitle: 'Edmond OK Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Edmond OK. Expert service for restaurants, UCO campus dining, and commercial kitchens. Cooking, refrigeration, HVAC, espresso. 24/7 emergency.',
    seoKeyword: 'Edmond OK commercial kitchen equipment repair',
  },
  {
    slug: 'moore-ok',
    city: 'Moore',
    state: 'OK',
    status: 'active' as const,
    tagline: 'Serving Moore, South OKC & Mid-Del Area',
    phone: '(405) 555-8247',
    phoneHref: 'tel:+14055558247',
    serviceArea: ['Moore', 'South Oklahoma City', 'Midwest City', 'Del City', 'Norman', 'Newcastle', 'Tinker AFB Area', 'Valley Brook', 'Oklahoma City'],
    description: 'True Commercial Service delivers reliable commercial kitchen equipment repair in Moore, OK and the Mid-Del area. We serve restaurants along 19th Street, fast-food chains on I-35, and institutional kitchens across South OKC. Fast response, fair pricing, and techs who know your equipment.',
    seoTitle: 'Moore OK Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Moore OK. Serving restaurants, chains, and commercial kitchens in Moore, Midwest City, Del City, and South OKC. 24/7 emergency service.',
    seoKeyword: 'Moore OK commercial kitchen equipment repair',
  },
  {
    slug: 'stillwater-ok',
    city: 'Stillwater',
    state: 'OK',
    status: 'active' as const,
    tagline: 'Serving Stillwater, OSU Campus & North Central OK',
    phone: '(405) 555-8247',
    phoneHref: 'tel:+14055558247',
    serviceArea: ['Stillwater', 'Perkins', 'Cushing', 'Perry', 'Pawnee', 'Ripley', 'Glencoe', 'Yale', 'Drumright'],
    description: 'True Commercial Service provides expert commercial kitchen equipment repair in Stillwater, OK. We keep the restaurants on The Strip, OSU campus dining halls, and commercial kitchens across Payne County running with fast response times and factory-trained technicians.',
    seoTitle: 'Stillwater OK Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Stillwater OK. Serving restaurants, OSU campus dining, bars, and commercial kitchens. Cooking, refrigeration, HVAC, ice machines.',
    seoKeyword: 'Stillwater OK commercial kitchen equipment repair',
  },

  // ─── NORTHERN NJ / NYC METRO ──────────────────────────────────
  {
    slug: 'elizabeth-nj',
    city: 'Elizabeth',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Elizabeth, Union County & the NJ/NYC Metro',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Elizabeth', 'Linden', 'Roselle', 'Roselle Park', 'Rahway', 'Clark', 'Hillside', 'Union', 'Cranford', 'Kenilworth'],
    description: 'True Commercial Service is launching in Elizabeth, NJ — our home base for serving Union County and the greater Northern NJ metro. Elizabeth has over 1,200 restaurants and food establishments, and we\'re bringing the tech-forward equipment repair service this market needs. AI-powered diagnostics, 24/7 emergency response, and factory-trained technicians.',
    seoTitle: 'Elizabeth NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Elizabeth NJ. Serving restaurants, delis, and commercial kitchens across Union County. Refrigeration, cooking, HVAC, ice machines. 24/7 emergency service.',
    seoKeyword: 'Elizabeth NJ commercial kitchen equipment repair',
  },
  {
    slug: 'newark-nj',
    city: 'Newark',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Newark, the Ironbound & Essex County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Newark', 'Ironbound', 'East Orange', 'Orange', 'Irvington', 'Belleville', 'Bloomfield', 'Nutley', 'Montclair', 'Maplewood'],
    description: 'True Commercial Service is bringing expert commercial kitchen equipment repair to Newark and Essex County. The Ironbound alone has hundreds of restaurants — Portuguese, Spanish, Brazilian, and more — all relying on commercial kitchen equipment that needs expert service. We deliver fast response, fair pricing, and AI-powered diagnostics.',
    seoTitle: 'Newark NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Newark NJ. Serving the Ironbound, Downtown Newark, and Essex County restaurants. Refrigeration, cooking, HVAC, espresso machines. 24/7 emergency.',
    seoKeyword: 'Newark NJ commercial kitchen equipment repair',
  },
  {
    slug: 'jersey-city-nj',
    city: 'Jersey City',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Jersey City, Hoboken & Hudson County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Jersey City', 'Hoboken', 'Union City', 'North Bergen', 'West New York', 'Weehawken', 'Bayonne', 'Secaucus', 'Kearny', 'Harrison'],
    description: 'True Commercial Service is expanding to Jersey City and Hudson County — one of the fastest-growing restaurant markets on the East Coast. From the waterfront restaurants in Downtown JC to the brunch spots on Washington Street in Hoboken, we\'re building the equipment repair operation Hudson County deserves.',
    seoTitle: 'Jersey City NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Jersey City and Hoboken NJ. Serving restaurants, cafes, and commercial kitchens across Hudson County. 24/7 emergency service.',
    seoKeyword: 'Jersey City NJ commercial kitchen equipment repair',
  },
  {
    slug: 'union-county-nj',
    city: 'Union County',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving All of Union County, NJ',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Elizabeth', 'Plainfield', 'Westfield', 'Summit', 'Scotch Plains', 'Cranford', 'Linden', 'Rahway', 'Roselle', 'Springfield', 'Clark', 'Mountainside', 'Berkeley Heights', 'New Providence'],
    description: 'True Commercial Service is Union County\'s incoming commercial kitchen equipment repair specialist. From the diverse restaurant scene in Elizabeth and Plainfield to the upscale dining in Westfield and Summit, we provide expert repair for every type of commercial kitchen equipment with 24/7 emergency response and AI-powered diagnostics.',
    seoTitle: 'Union County NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair across Union County NJ. Elizabeth, Westfield, Plainfield, Summit, Cranford, and more. Refrigeration, cooking, HVAC. 24/7 emergency service.',
    seoKeyword: 'Union County NJ commercial kitchen equipment repair',
  },
  {
    slug: 'paterson-nj',
    city: 'Paterson',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Paterson, Passaic County & North Jersey',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Paterson', 'Passaic', 'Clifton', 'Wayne', 'Totowa', 'Little Falls', 'Woodland Park', 'Haledon', 'Hawthorne', 'Fair Lawn'],
    description: 'True Commercial Service is bringing reliable commercial kitchen equipment repair to Paterson and Passaic County. Paterson\'s vibrant food scene — from Middle Eastern bakeries on Main Street to Latin restaurants throughout the city — deserves a service company that shows up fast, diagnoses right, and fixes it the first time.',
    seoTitle: 'Paterson NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Paterson and Passaic County NJ. Serving restaurants, bakeries, and commercial kitchens. Refrigeration, cooking, HVAC. 24/7 emergency.',
    seoKeyword: 'Paterson NJ commercial kitchen equipment repair',
  },
  {
    slug: 'new-brunswick-nj',
    city: 'New Brunswick',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving New Brunswick, Middlesex County & Central NJ',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['New Brunswick', 'Edison', 'Woodbridge', 'Perth Amboy', 'Piscataway', 'Highland Park', 'South Plainfield', 'Metuchen', 'Sayreville', 'Old Bridge'],
    description: 'True Commercial Service is expanding to New Brunswick and Middlesex County. From Rutgers campus dining to the thriving restaurant scene on George Street and Route 1, we deliver expert commercial kitchen equipment repair with the speed, technology, and expertise Central NJ operators need.',
    seoTitle: 'New Brunswick NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in New Brunswick and Middlesex County NJ. Serving restaurants, Rutgers dining, and commercial kitchens. 24/7 emergency service.',
    seoKeyword: 'New Brunswick NJ commercial kitchen equipment repair',
  },

  // ─── ATLANTA METRO ────────────────────────────────────────────
  {
    slug: 'atlanta',
    city: 'Atlanta',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Metro Atlanta and North Georgia',
    phone: '(470) 555-8247',
    phoneHref: 'tel:+14705558247',
    serviceArea: ['Atlanta', 'Midtown', 'Buckhead', 'Decatur', 'East Atlanta', 'West Midtown', 'Old Fourth Ward', 'Virginia-Highland', 'Ponce City', 'Grant Park'],
    description: 'True Commercial Service is expanding to Atlanta — bringing our tech-forward approach to commercial kitchen equipment repair across Metro Atlanta. From the Buford Highway food corridor to the Westside Provisions District, Atlanta\'s restaurant scene deserves better equipment service.',
    seoTitle: 'Atlanta Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair coming to Metro Atlanta. Expert cooking, refrigeration, HVAC service for restaurants, grocery stores, and institutions.',
    seoKeyword: 'Atlanta commercial kitchen equipment repair',
  },
  {
    slug: 'marietta-ga',
    city: 'Marietta',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Marietta, Cobb County & Northwest Metro Atlanta',
    phone: '(470) 555-8247',
    phoneHref: 'tel:+14705558247',
    serviceArea: ['Marietta', 'Kennesaw', 'Smyrna', 'Acworth', 'Powder Springs', 'Austell', 'Vinings', 'Mableton', 'Cumberland', 'Sandy Plains'],
    description: 'True Commercial Service is bringing expert commercial kitchen equipment repair to Marietta and Cobb County. From the Marietta Square restaurants to the chain operations along I-75 and Barrett Parkway, we\'re building the service infrastructure Cobb County\'s growing food industry needs.',
    seoTitle: 'Marietta GA Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Marietta and Cobb County GA. Serving restaurants, commercial kitchens, and institutions. Refrigeration, cooking, HVAC. 24/7 emergency.',
    seoKeyword: 'Marietta GA commercial kitchen equipment repair',
  },
  {
    slug: 'decatur-ga',
    city: 'Decatur',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Decatur, DeKalb County & East Metro Atlanta',
    phone: '(470) 555-8247',
    phoneHref: 'tel:+14705558247',
    serviceArea: ['Decatur', 'Stone Mountain', 'Tucker', 'Dunwoody', 'Sandy Springs', 'Chamblee', 'Doraville', 'Brookhaven', 'Clarkston', 'Lithonia'],
    description: 'True Commercial Service is expanding to Decatur and DeKalb County. Decatur\'s award-winning restaurant scene and the Buford Highway international food corridor represent some of the most exciting — and most demanding — commercial kitchens in Georgia. We\'re building a service operation that matches that energy.',
    seoTitle: 'Decatur GA Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Decatur and DeKalb County GA. Serving restaurants, Buford Highway food corridor, and commercial kitchens. 24/7 emergency service.',
    seoKeyword: 'Decatur GA commercial kitchen equipment repair',
  },
  {
    slug: 'roswell-ga',
    city: 'Roswell',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Roswell, Alpharetta & North Fulton County',
    phone: '(470) 555-8247',
    phoneHref: 'tel:+14705558247',
    serviceArea: ['Roswell', 'Alpharetta', 'Johns Creek', 'Milton', 'Cumming', 'Suwanee', 'Duluth', 'Norcross', 'Peachtree Corners', 'Lawrenceville'],
    description: 'True Commercial Service is launching in Roswell and North Fulton County — the suburbs driving Metro Atlanta\'s restaurant boom. From Canton Street restaurants in Roswell to the Avalon district in Alpharetta, we deliver expert commercial kitchen equipment repair with AI-powered diagnostics and same-day emergency response.',
    seoTitle: 'Roswell GA Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Roswell, Alpharetta, and North Fulton County GA. Serving restaurants and commercial kitchens. 24/7 emergency service.',
    seoKeyword: 'Roswell GA commercial kitchen equipment repair',
  },
];

export const VERTICALS = [
  {
    slug: 'restaurants',
    title: 'Restaurants',
    icon: 'UtensilsCrossed',
    description: 'From fast casual to fine dining. We know the urgency of a kitchen going down during service.',
    longDescription: 'A broken fryer at 5pm on a Friday isn\'t a maintenance issue — it\'s a revenue emergency. We get that. True Commercial Service is built around the reality of restaurant operations: tight margins, high volume, and zero tolerance for downtime. Our response times, diagnostic speed, and first-time fix rates reflect that urgency.',
    painPoints: ['Equipment failures during peak hours', 'Inconsistent service from rotating techs', 'Long wait times for parts', 'Lack of manufacturer expertise'],
  },
  {
    slug: 'grocery-stores',
    title: 'Grocery Stores',
    icon: 'ShoppingCart',
    description: 'Refrigeration-critical environments with zero tolerance for temperature excursions.',
    longDescription: 'When your walk-in goes down, you\'re not just losing equipment uptime — you\'re losing inventory. Grocery and convenience store operators need a service partner who understands refrigeration urgency, health code compliance, and the specific demands of high-volume retail food environments.',
    painPoints: ['Perishable inventory at risk', 'Multi-unit consistency', 'Health department compliance', 'After-hours emergency needs'],
  },
  {
    slug: 'schools-institutions',
    title: 'Schools & Institutions',
    icon: 'GraduationCap',
    description: 'University dining, K-12 cafeterias, hospital kitchens, and government facilities.',
    longDescription: 'Institutional foodservice operates on fixed budgets with non-negotiable feeding schedules. When equipment goes down at a school cafeteria or hospital kitchen, there\'s no backup plan. We work with institutional operators to build PM programs that prevent emergencies and respond fast when they happen.',
    painPoints: ['Fixed feeding schedules', 'Budget constraints', 'Procurement processes', 'Code and compliance requirements'],
  },
  {
    slug: 'hotels',
    title: 'Hotels & Hospitality',
    icon: 'Building2',
    description: 'Full-service hotel kitchens, banquet facilities, room service operations.',
    longDescription: 'Hotel foodservice is complex — multiple outlets, banquet operations, room service, and often a coffee program that\'s the first touchpoint for every guest. We support hotel engineering teams with responsive service that understands the hospitality standard.',
    painPoints: ['Multiple foodservice outlets', 'Guest-facing quality standards', 'Banquet and event deadlines', '24/7 operational demands'],
  },
];

export const STATS = [
  { value: '4hr', label: 'Average Response Time' },
  { value: '94%', label: 'First-Time Fix Rate' },
  { value: '24/7', label: 'Emergency Service' },
  { value: '90-Day', label: 'Parts & Labor Guarantee' },
];

export const MANUFACTURERS = [
  'Rational', 'Hoshizaki', 'True Manufacturing', 'Alto-Shaam',
  'Vulcan', 'Traulsen', 'Manitowoc', 'Blodgett',
  'La Marzocco', 'Carrier', 'Turbo Air', 'Scotsman',
  'Garland', 'Pitco', 'Delfield', 'Bunn',
];

export const TESTIMONIALS = [
  {
    quote: 'True Commercial showed up same day, diagnosed the issue in 20 minutes, and had our combi oven running before dinner service. Nobody else even called us back.',
    author: 'Michael R.',
    role: 'Executive Chef',
    location: 'Oklahoma City, OK',
  },
  {
    quote: 'We switched from a national provider to True and the difference is night and day. Actual humans who know our equipment and show up when they say they will.',
    author: 'Sarah K.',
    role: 'Director of Operations',
    location: 'Norman, OK',
  },
  {
    quote: 'The PM program has already paid for itself. We haven\'t had an emergency call in six months. That\'s unheard of for a kitchen our size.',
    author: 'David T.',
    role: 'Facilities Manager',
    location: 'Edmond, OK',
  },
];
