export const COMPANY = {
  name: 'True Commercial Service',
  legal: 'True Commercial Service LLC',
  phone: '(908) 743-8688',
  phoneHref: 'tel:+19087438688',
  emergencyPhone: '(908) 743-8688',
  emergencyPhoneHref: 'tel:+19087438688',
  email: 'service@choosetrue.com',
  tagline: 'Commercial Kitchen Equipment Repair. Done Right.',
  description: 'True Commercial Service is a tech-forward commercial kitchen equipment repair and ventilation company serving Northern New Jersey, New York City, Connecticut, and Atlanta.',
};

export const SERVICES = [
  {
    slug: 'cooking-equipment',
    title: 'Cooking Equipment Repair',
    shortTitle: 'Cooking',
    icon: 'Flame',
    description: 'Ovens, ranges, fryers, griddles, steamers, and more. Factory-trained techs who fix it right the first time.',
    longDescription: 'From combi ovens to conveyor ovens, charbroilers to tilt skillets — we repair every major brand of commercial cooking equipment. Our technicians carry manufacturer certifications and the diagnostic tools to identify issues fast. No guesswork. No repeat visits.',
    equipment: ['Combi Ovens', 'Convection Ovens', 'Conveyor Ovens', 'Fryers', 'Griddles', 'Charbroilers', 'Ranges', 'Steamers', 'Tilt Skillets', 'Salamanders', 'Rotisseries', 'Induction Cooktops'],
    brands: ['Rational', 'Alto-Shaam', 'Vulcan', 'Garland', 'Blodgett', 'Henny Penny', 'Pitco', 'Frymaster', 'Cleveland', 'TurboChef'],
  },
  {
    slug: 'refrigeration',
    title: 'Commercial Refrigeration Repair',
    shortTitle: 'Refrigeration',
    icon: 'Thermometer',
    description: 'Walk-in coolers, reach-ins, prep tables, display cases. Fast response to protect your inventory.',
    longDescription: 'Refrigeration failures cost you money every minute. We prioritize refrigeration calls because your inventory is on the line. Walk-in coolers, reach-in units, prep tables, display merchandisers — we service them all with the urgency they demand.',
    equipment: ['Walk-In Coolers', 'Walk-In Freezers', 'Reach-In Refrigerators', 'Prep Tables', 'Display Cases', 'Ice Cream Cabinets', 'Blast Chillers', 'Undercounter Units', 'Refrigerated Bases'],
    brands: ['True Manufacturing', 'Traulsen', 'Hoshizaki', 'Turbo Air', 'Continental', 'Beverage-Air', 'Delfield', 'Randell', 'Master-Bilt'],
  },
  {
    slug: 'hvac',
    title: 'Commercial HVAC Service',
    shortTitle: 'HVAC',
    icon: 'Wind',
    description: 'Rooftop units, kitchen ventilation, makeup air. Keep your kitchen and dining room comfortable year-round.',
    longDescription: 'Commercial kitchens generate massive amounts of heat. Your HVAC system is working harder than anywhere else. We maintain and repair rooftop units, split systems, kitchen ventilation hoods, makeup air units, and exhaust fans — keeping your staff comfortable and your kitchen code-compliant.',
    equipment: ['Rooftop Units (RTUs)', 'Split Systems', 'Kitchen Exhaust Hoods', 'Makeup Air Units', 'Exhaust Fans', 'VRF Systems', 'Walk-In Unit Coolers', 'Condensing Units'],
    brands: ['Carrier', 'Trane', 'Lennox', 'Daikin', 'Bard', 'Captive Aire', 'Accurex'],
  },
  {
    slug: 'beverage-equipment',
    title: 'Beverage Equipment Repair',
    shortTitle: 'Beverage',
    icon: 'GlassWater',
    description: 'Ice machines, fountain dispensers, tea brewers, juice systems. Keep the drinks flowing.',
    longDescription: 'Nothing slows down service like a broken ice machine or a downed fountain system. We repair and maintain all major brands of commercial beverage equipment — from Hoshizaki and Manitowoc ice machines to Bunn brewers and fountain systems.',
    equipment: ['Ice Machines', 'Fountain Dispensers', 'Tea Brewers', 'Coffee Brewers', 'Juice Dispensers', 'Beer Systems', 'Water Filtration', 'Carbonation Systems'],
    brands: ['Hoshizaki', 'Manitowoc', 'Scotsman', 'Ice-O-Matic', 'Bunn', 'Cornelius', 'Lancer', 'Wunder-Bar'],
  },
  {
    slug: 'espresso-machines',
    title: 'Espresso Machine Repair',
    shortTitle: 'Espresso',
    icon: 'Coffee',
    description: 'Specialized service for commercial espresso machines. Multi-group, superautomatic, and grinders.',
    longDescription: 'Commercial espresso machines are precision instruments. Most service companies won\'t touch them. We will — and we\'ll fix them right. From PID tuning to group head rebuilds, boiler descaling to grinder calibration, our techs have deep training on the machines that matter to your coffee program.',
    equipment: ['Multi-Group Espresso Machines', 'Superautomatic Machines', 'Commercial Grinders', 'Steam Wands', 'Group Heads', 'Boilers', 'Water Treatment Systems'],
    brands: ['La Marzocco', 'Nuova Simonelli', 'La Cimbali', 'Rancilio', 'Slayer', 'Synesso', 'Mazzer', 'Mahlkönig'],
  },
  {
    slug: 'pollution-control',
    title: 'Kitchen Exhaust Pollution Control (ESP/PCU)',
    shortTitle: 'Pollution Control',
    icon: 'Wind',
    description: 'ESP cell cleaning, ecology unit service, and smoke control system maintenance. NYC Local Law 38 compliance. Avoid $10K+ fines.',
    longDescription: 'NYC Local Law 38 requires every commercial kitchen with charbroiling, grilling, or frying to have a functioning pollution control unit on the exhaust. Electrostatic precipitators (ESPs), ecology units, and Smoke Hog systems all need quarterly cleaning to stay compliant. We clean the collector cells, replace ionizer wires, service power supplies, and document everything for your DEP inspection.',
    equipment: ['Electrostatic Precipitators (ESP)', 'Ecology Rooftop Units', 'Smoke Hog Systems', 'Carbon/Charcoal Odor Filters', 'UV Oxidation Systems', 'Catalytic Oxidizers', 'Pre-Filters and Post-Filters', 'ESP Power Supplies and Controls'],
    brands: ['Smoke Hog', 'CaptiveAire', 'Halton', 'Ecology', 'Accurex', 'Greenheck', 'Streivor', 'PPC Air'],
  },
  {
    slug: 'preventive-maintenance',
    title: 'Preventive Maintenance Agreements',
    shortTitle: 'PM Plans',
    icon: 'ShieldCheck',
    description: 'Scheduled maintenance that extends equipment life and prevents costly emergency calls.',
    longDescription: 'The smartest operators don\'t wait for breakdowns. Our Preventive Maintenance agreements put your equipment on a scheduled service cadence — cleaning, calibrating, and inspecting before small issues become expensive emergencies. We build custom PM plans based on your equipment inventory and usage patterns.',
    equipment: ['Full Kitchen PM Programs', 'Refrigeration-Only PM', 'HVAC PM', 'Custom Equipment Audits', 'Seasonal Tune-Ups'],
    brands: [],
  },
];

export const LOCATIONS = [
  // ─── NORTHERN NJ / NYC METRO ──────────────────────────────────
  {
    slug: 'elizabeth-nj',
    city: 'Elizabeth',
    state: 'NJ',
    status: 'active' as const,
    tagline: 'Serving Elizabeth, Union County & the NJ/NYC Metro',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Elizabeth', 'Linden', 'Roselle', 'Roselle Park', 'Rahway', 'Clark', 'Hillside', 'Union', 'Cranford', 'Kenilworth'],
    description: 'True Commercial Service is launching in Elizabeth, NJ — our home base for serving Union County and the greater Northern NJ metro. Elizabeth has over 1,200 restaurants and food establishments, and we\'re bringing the tech-forward equipment repair service this market needs. AI-powered diagnostics, 24/7 emergency response, and factory-trained technicians.',
    seoTitle: 'Elizabeth NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Elizabeth NJ. Serving restaurants, delis, and commercial kitchens across Union County. Refrigeration, cooking, HVAC, ice machines. 24/7 emergency service.',
    seoKeyword: 'Elizabeth NJ commercial kitchen equipment repair',
  },
  {
    slug: 'newark-nj',
    city: 'Newark',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Newark, the Ironbound & Essex County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Newark', 'Ironbound', 'East Orange', 'Orange', 'Irvington', 'Belleville', 'Bloomfield', 'Nutley', 'Montclair', 'Maplewood'],
    description: 'True Commercial Service is bringing expert commercial kitchen equipment repair to Newark and Essex County. The Ironbound alone has hundreds of restaurants — Portuguese, Spanish, Brazilian, and more — all relying on commercial kitchen equipment that needs expert service. We deliver fast response, fair pricing, and AI-powered diagnostics.',
    seoTitle: 'Newark NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Newark NJ. Serving the Ironbound, Downtown Newark, and Essex County restaurants. Refrigeration, cooking, HVAC, espresso machines. 24/7 emergency.',
    seoKeyword: 'Newark NJ commercial kitchen equipment repair',
  },
  {
    slug: 'jersey-city-nj',
    city: 'Jersey City',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Jersey City, Hoboken & Hudson County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Jersey City', 'Hoboken', 'Union City', 'North Bergen', 'West New York', 'Weehawken', 'Bayonne', 'Secaucus', 'Kearny', 'Harrison'],
    description: 'True Commercial Service is expanding to Jersey City and Hudson County — one of the fastest-growing restaurant markets on the East Coast. From the waterfront restaurants in Downtown JC to the brunch spots on Washington Street in Hoboken, we\'re building the equipment repair operation Hudson County deserves.',
    seoTitle: 'Jersey City NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Jersey City and Hoboken NJ. Serving restaurants, cafes, and commercial kitchens across Hudson County. 24/7 emergency service.',
    seoKeyword: 'Jersey City NJ commercial kitchen equipment repair',
  },
  {
    slug: 'union-county-nj',
    city: 'Union County',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving All of Union County, NJ',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Elizabeth', 'Plainfield', 'Westfield', 'Summit', 'Scotch Plains', 'Cranford', 'Linden', 'Rahway', 'Roselle', 'Springfield', 'Clark', 'Mountainside', 'Berkeley Heights', 'New Providence'],
    description: 'True Commercial Service is Union County\'s incoming commercial kitchen equipment repair specialist. From the diverse restaurant scene in Elizabeth and Plainfield to the upscale dining in Westfield and Summit, we provide expert repair for every type of commercial kitchen equipment with 24/7 emergency response and AI-powered diagnostics.',
    seoTitle: 'Union County NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair across Union County NJ. Elizabeth, Westfield, Plainfield, Summit, Cranford, and more. Refrigeration, cooking, HVAC. 24/7 emergency service.',
    seoKeyword: 'Union County NJ commercial kitchen equipment repair',
  },
  {
    slug: 'paterson-nj',
    city: 'Paterson',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Paterson, Passaic County & North Jersey',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Paterson', 'Passaic', 'Clifton', 'Wayne', 'Totowa', 'Little Falls', 'Woodland Park', 'Haledon', 'Hawthorne', 'Fair Lawn'],
    description: 'True Commercial Service is bringing reliable commercial kitchen equipment repair to Paterson and Passaic County. Paterson\'s vibrant food scene — from Middle Eastern bakeries on Main Street to Latin restaurants throughout the city — deserves a service company that shows up fast, diagnoses right, and fixes it the first time.',
    seoTitle: 'Paterson NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Paterson and Passaic County NJ. Serving restaurants, bakeries, and commercial kitchens. Refrigeration, cooking, HVAC. 24/7 emergency.',
    seoKeyword: 'Paterson NJ commercial kitchen equipment repair',
  },
  {
    slug: 'new-brunswick-nj',
    city: 'New Brunswick',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving New Brunswick, Middlesex County & Central NJ',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['New Brunswick', 'Edison', 'Woodbridge', 'Perth Amboy', 'Piscataway', 'Highland Park', 'South Plainfield', 'Metuchen', 'Sayreville', 'Old Bridge'],
    description: 'True Commercial Service is expanding to New Brunswick and Middlesex County. From Rutgers campus dining to the thriving restaurant scene on George Street and Route 1, we deliver expert commercial kitchen equipment repair with the speed, technology, and expertise Central NJ operators need.',
    seoTitle: 'New Brunswick NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in New Brunswick and Middlesex County NJ. Serving restaurants, Rutgers dining, and commercial kitchens. 24/7 emergency service.',
    seoKeyword: 'New Brunswick NJ commercial kitchen equipment repair',
  },

  // ─── NEW YORK CITY ─────────────────────────────────────────────
  {
    slug: 'new-york-city',
    city: 'New York City',
    state: 'NY',
    status: 'coming-soon' as const,
    tagline: 'Serving All Five Boroughs of NYC',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Manhattan', 'Brooklyn', 'Queens', 'The Bronx', 'Staten Island'],
    description: 'True Commercial Service is bringing tech-forward commercial kitchen equipment repair to New York City — all five boroughs. NYC has over 27,000 restaurants, thousands of delis and bodegas, hotel kitchens, hospital cafeterias, and school dining facilities. Every one of them runs on commercial equipment that breaks down. We\'re building the repair operation the city deserves — fast response, AI-powered diagnostics, factory-trained technicians, and 24/7 emergency service.',
    seoTitle: 'New York City Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in NYC. Serving Manhattan, Brooklyn, Queens, The Bronx, and Staten Island. Restaurants, hotels, institutions. 24/7 emergency service.',
    seoKeyword: 'New York City commercial kitchen equipment repair',
  },
  {
    slug: 'manhattan-ny',
    city: 'Manhattan',
    state: 'NY',
    status: 'coming-soon' as const,
    tagline: 'Serving Manhattan — Midtown to the Financial District',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Midtown', 'Lower Manhattan', 'Upper East Side', 'Upper West Side', 'Chelsea', 'Greenwich Village', 'SoHo', 'Tribeca', 'Harlem', 'East Village', 'Hell\'s Kitchen', 'Financial District', 'Chinatown', 'Little Italy'],
    description: 'True Commercial Service is launching in Manhattan — the most demanding restaurant market in the world. From Michelin-starred kitchens in Tribeca to the pizza shops of Hell\'s Kitchen, hotel banquet facilities on Park Avenue to campus dining at Columbia and NYU, Manhattan operators need equipment repair that matches their urgency. We deliver AI-powered diagnostics, same-day emergency response, and factory-certified technicians who know the equipment inside and out.',
    seoTitle: 'Manhattan NY Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Manhattan. Midtown, Downtown, Upper East Side, Chelsea, SoHo, Harlem, and more. Restaurants, hotels, institutions. 24/7 emergency.',
    seoKeyword: 'Manhattan commercial kitchen equipment repair',
  },
  {
    slug: 'brooklyn-ny',
    city: 'Brooklyn',
    state: 'NY',
    status: 'coming-soon' as const,
    tagline: 'Serving Brooklyn — Williamsburg to Bay Ridge',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Williamsburg', 'DUMBO', 'Park Slope', 'Bushwick', 'Crown Heights', 'Bay Ridge', 'Sunset Park', 'Flatbush', 'Greenpoint', 'Red Hook', 'Bed-Stuy', 'Borough Park', 'Brighton Beach', 'Bensonhurst'],
    description: 'True Commercial Service is expanding to Brooklyn — one of the most dynamic food scenes in the country. From the craft cocktail bars of Williamsburg to the taquerias of Sunset Park, the Russian restaurants of Brighton Beach to the bakeries of Borough Park, Brooklyn\'s kitchens are as diverse as they come. We\'re bringing expert equipment repair with the speed and technology Brooklyn operators demand.',
    seoTitle: 'Brooklyn NY Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Brooklyn. Williamsburg, Park Slope, DUMBO, Bushwick, Bay Ridge, and all Brooklyn neighborhoods. Restaurants, cafes, bakeries. 24/7 emergency.',
    seoKeyword: 'Brooklyn commercial kitchen equipment repair',
  },
  {
    slug: 'queens-ny',
    city: 'Queens',
    state: 'NY',
    status: 'coming-soon' as const,
    tagline: 'Serving Queens — Astoria to Jamaica',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Astoria', 'Long Island City', 'Flushing', 'Jackson Heights', 'Jamaica', 'Forest Hills', 'Elmhurst', 'Woodside', 'Bayside', 'Ridgewood', 'Corona', 'Sunnyside', 'Rego Park', 'Fresh Meadows'],
    description: 'True Commercial Service is coming to Queens — the most ethnically diverse county in the United States and home to some of NYC\'s best food. From the Greek tavernas of Astoria to the dim sum palaces of Flushing, the Colombian bakeries of Jackson Heights to the Indian restaurants of Hillside Avenue, Queens kitchens need a service company that shows up fast and fixes it right the first time.',
    seoTitle: 'Queens NY Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Queens. Astoria, Flushing, Jackson Heights, Long Island City, Jamaica, and all Queens neighborhoods. 24/7 emergency service.',
    seoKeyword: 'Queens commercial kitchen equipment repair',
  },
  {
    slug: 'bronx-ny',
    city: 'The Bronx',
    state: 'NY',
    status: 'coming-soon' as const,
    tagline: 'Serving The Bronx — Arthur Avenue to City Island',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['South Bronx', 'Fordham', 'Arthur Avenue', 'Riverdale', 'Kingsbridge', 'Pelham Bay', 'City Island', 'Mott Haven', 'Hunts Point', 'Parkchester', 'Throggs Neck', 'Morris Park'],
    description: 'True Commercial Service is expanding to The Bronx — from the legendary Italian restaurants on Arthur Avenue to the seafood spots on City Island, the Dominican bakeries of Fordham to the booming restaurant scene in Mott Haven and the South Bronx. Plus Hunts Point Market, the largest food distribution center in the world, surrounded by commercial kitchens that need reliable equipment service.',
    seoTitle: 'Bronx NY Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in The Bronx. Arthur Avenue, Fordham, Riverdale, Mott Haven, City Island, and all Bronx neighborhoods. 24/7 emergency service.',
    seoKeyword: 'Bronx commercial kitchen equipment repair',
  },
  {
    slug: 'staten-island-ny',
    city: 'Staten Island',
    state: 'NY',
    status: 'coming-soon' as const,
    tagline: 'Serving Staten Island — St. George to Tottenville',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['St. George', 'Stapleton', 'New Dorp', 'Tottenville', 'Great Kills', 'Eltingville', 'Todt Hill', 'West Brighton', 'Port Richmond', 'Willowbrook', 'Huguenot', 'Annadale'],
    description: 'True Commercial Service is bringing expert commercial kitchen equipment repair to Staten Island. From the restaurants along Hylan Boulevard to the waterfront dining in St. George, the Italian spots on Forest Avenue to the growing food scene across the South Shore, Staten Island operators deserve the same fast, tech-forward equipment service as the rest of NYC.',
    seoTitle: 'Staten Island NY Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair on Staten Island. St. George, New Dorp, Tottenville, Great Kills, and all SI neighborhoods. Restaurants, pizzerias, delis. 24/7 emergency.',
    seoKeyword: 'Staten Island commercial kitchen equipment repair',
  },

  // ─── CONNECTICUT ───────────────────────────────────────────────
  {
    slug: 'stamford-ct',
    city: 'Stamford',
    state: 'CT',
    status: 'coming-soon' as const,
    tagline: 'Serving Stamford, Greenwich & Fairfield County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Stamford', 'Greenwich', 'Darien', 'New Canaan', 'Norwalk', 'Westport', 'Fairfield', 'Bridgeport', 'Cos Cob', 'Old Greenwich'],
    description: 'True Commercial Service is bringing expert commercial kitchen ventilation and equipment repair to Stamford and Fairfield County. From the restaurants along Bedford Street to the hotel kitchens in Harbor Point, Stamford\'s growing food scene needs dedicated kitchen ventilation service.',
    seoTitle: 'Stamford CT Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair and ventilation service in Stamford CT. Serving restaurants, hotels, and commercial kitchens across Fairfield County. Air balancing, ESP service, exhaust fans. 24/7 emergency.',
    seoKeyword: 'Stamford CT commercial kitchen equipment repair',
  },
  {
    slug: 'norwalk-ct',
    city: 'Norwalk',
    state: 'CT',
    status: 'coming-soon' as const,
    tagline: 'Serving Norwalk, Westport & Coastal Fairfield County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Norwalk', 'Westport', 'Weston', 'Wilton', 'Ridgefield', 'Redding', 'Easton', 'SoNo District', 'Rowayton'],
    description: 'True Commercial Service is expanding to Norwalk and coastal Fairfield County. The SoNo district\'s restaurant boom, Westport\'s dining scene, and the institutional kitchens throughout the area all need expert kitchen ventilation and equipment service.',
    seoTitle: 'Norwalk CT Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair and ventilation service in Norwalk CT. Serving SoNo, Westport, and Fairfield County restaurants. Air balancing, ESP cleaning, exhaust fans.',
    seoKeyword: 'Norwalk CT commercial kitchen equipment repair',
  },
  {
    slug: 'bridgeport-ct',
    city: 'Bridgeport',
    state: 'CT',
    status: 'coming-soon' as const,
    tagline: 'Serving Bridgeport, Trumbull & Greater Bridgeport',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Bridgeport', 'Trumbull', 'Stratford', 'Shelton', 'Milford', 'Fairfield', 'Monroe', 'Easton', 'Black Rock'],
    description: 'True Commercial Service is bringing kitchen ventilation expertise to Bridgeport and Greater Bridgeport. From downtown restaurants to the institutional kitchens at Bridgeport Hospital and Sacred Heart University, we deliver air balancing, ESP service, and equipment repair.',
    seoTitle: 'Bridgeport CT Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair and ventilation service in Bridgeport CT. Serving restaurants, hospitals, and commercial kitchens. Air balancing, ESP service, exhaust fan repair.',
    seoKeyword: 'Bridgeport CT commercial kitchen equipment repair',
  },
  {
    slug: 'new-haven-ct',
    city: 'New Haven',
    state: 'CT',
    status: 'coming-soon' as const,
    tagline: 'Serving New Haven, Yale & the CT Shoreline',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['New Haven', 'West Haven', 'East Haven', 'Hamden', 'North Haven', 'Branford', 'Guilford', 'Madison', 'Orange', 'Woodbridge'],
    description: 'True Commercial Service is expanding to New Haven — home to some of Connecticut\'s best restaurants, Yale University\'s dining operations, and the legendary pizza on Wooster Street. New Haven\'s diverse and growing food scene deserves expert kitchen ventilation service.',
    seoTitle: 'New Haven CT Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair and ventilation service in New Haven CT. Serving restaurants, Yale dining, and commercial kitchens. Air balancing, ESP cleaning, exhaust fans.',
    seoKeyword: 'New Haven CT commercial kitchen equipment repair',
  },

  // ─── ATLANTA METRO ────────────────────────────────────────────
  {
    slug: 'atlanta',
    city: 'Atlanta',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Metro Atlanta and North Georgia',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Atlanta', 'Midtown', 'Buckhead', 'Decatur', 'East Atlanta', 'West Midtown', 'Old Fourth Ward', 'Virginia-Highland', 'Ponce City', 'Grant Park'],
    description: 'True Commercial Service is expanding to Atlanta — bringing our tech-forward approach to commercial kitchen equipment repair across Metro Atlanta. From the Buford Highway food corridor to the Westside Provisions District, Atlanta\'s restaurant scene deserves better equipment service.',
    seoTitle: 'Atlanta Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair coming to Metro Atlanta. Expert cooking, refrigeration, HVAC service for restaurants, grocery stores, and institutions.',
    seoKeyword: 'Atlanta commercial kitchen equipment repair',
  },
  {
    slug: 'marietta-ga',
    city: 'Marietta',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Marietta, Cobb County & Northwest Metro Atlanta',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Marietta', 'Kennesaw', 'Smyrna', 'Acworth', 'Powder Springs', 'Austell', 'Vinings', 'Mableton', 'Cumberland', 'Sandy Plains'],
    description: 'True Commercial Service is bringing expert commercial kitchen equipment repair to Marietta and Cobb County. From the Marietta Square restaurants to the chain operations along I-75 and Barrett Parkway, we\'re building the service infrastructure Cobb County\'s growing food industry needs.',
    seoTitle: 'Marietta GA Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Marietta and Cobb County GA. Serving restaurants, commercial kitchens, and institutions. Refrigeration, cooking, HVAC. 24/7 emergency.',
    seoKeyword: 'Marietta GA commercial kitchen equipment repair',
  },
  {
    slug: 'decatur-ga',
    city: 'Decatur',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Decatur, DeKalb County & East Metro Atlanta',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Decatur', 'Stone Mountain', 'Tucker', 'Dunwoody', 'Sandy Springs', 'Chamblee', 'Doraville', 'Brookhaven', 'Clarkston', 'Lithonia'],
    description: 'True Commercial Service is expanding to Decatur and DeKalb County. Decatur\'s award-winning restaurant scene and the Buford Highway international food corridor represent some of the most exciting — and most demanding — commercial kitchens in Georgia. We\'re building a service operation that matches that energy.',
    seoTitle: 'Decatur GA Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Decatur and DeKalb County GA. Serving restaurants, Buford Highway food corridor, and commercial kitchens. 24/7 emergency service.',
    seoKeyword: 'Decatur GA commercial kitchen equipment repair',
  },
  {
    slug: 'roswell-ga',
    city: 'Roswell',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Roswell, Alpharetta & North Fulton County',
    phone: '(908) 743-8688',
    phoneHref: 'tel:+19087438688',
    serviceArea: ['Roswell', 'Alpharetta', 'Johns Creek', 'Milton', 'Cumming', 'Suwanee', 'Duluth', 'Norcross', 'Peachtree Corners', 'Lawrenceville'],
    description: 'True Commercial Service is launching in Roswell and North Fulton County — the suburbs driving Metro Atlanta\'s restaurant boom. From Canton Street restaurants in Roswell to the Avalon district in Alpharetta, we deliver expert commercial kitchen equipment repair with AI-powered diagnostics and same-day emergency response.',
    seoTitle: 'Roswell GA Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair in Roswell, Alpharetta, and North Fulton County GA. Serving restaurants and commercial kitchens. 24/7 emergency service.',
    seoKeyword: 'Roswell GA commercial kitchen equipment repair',
  },
];

export const VERTICALS = [
  {
    slug: 'restaurants',
    title: 'Restaurants',
    icon: 'UtensilsCrossed',
    description: 'From fast casual to fine dining. We know the urgency of a kitchen going down during service.',
    longDescription: 'A broken fryer at 5pm on a Friday isn\'t a maintenance issue — it\'s a revenue emergency. We get that. True Commercial Service is built around the reality of restaurant operations: tight margins, high volume, and zero tolerance for downtime. Our response times, diagnostic speed, and first-time fix rates reflect that urgency.',
    painPoints: ['Equipment failures during peak hours', 'Inconsistent service from rotating techs', 'Long wait times for parts', 'Lack of manufacturer expertise'],
  },
  {
    slug: 'grocery-stores',
    title: 'Grocery Stores',
    icon: 'ShoppingCart',
    description: 'Refrigeration-critical environments with zero tolerance for temperature excursions.',
    longDescription: 'When your walk-in goes down, you\'re not just losing equipment uptime — you\'re losing inventory. Grocery and convenience store operators need a service partner who understands refrigeration urgency, health code compliance, and the specific demands of high-volume retail food environments.',
    painPoints: ['Perishable inventory at risk', 'Multi-unit consistency', 'Health department compliance', 'After-hours emergency needs'],
  },
  {
    slug: 'schools-institutions',
    title: 'Schools & Institutions',
    icon: 'GraduationCap',
    description: 'University dining, K-12 cafeterias, hospital kitchens, and government facilities.',
    longDescription: 'Institutional foodservice operates on fixed budgets with non-negotiable feeding schedules. When equipment goes down at a school cafeteria or hospital kitchen, there\'s no backup plan. We work with institutional operators to build PM programs that prevent emergencies and respond fast when they happen.',
    painPoints: ['Fixed feeding schedules', 'Budget constraints', 'Procurement processes', 'Code and compliance requirements'],
  },
  {
    slug: 'hotels',
    title: 'Hotels & Hospitality',
    icon: 'Building2',
    description: 'Full-service hotel kitchens, banquet facilities, room service operations.',
    longDescription: 'Hotel foodservice is complex — multiple outlets, banquet operations, room service, and often a coffee program that\'s the first touchpoint for every guest. We support hotel engineering teams with responsive service that understands the hospitality standard.',
    painPoints: ['Multiple foodservice outlets', 'Guest-facing quality standards', 'Banquet and event deadlines', '24/7 operational demands'],
  },
];

// Directory & social profile URLs — update each as you register
// These feed into schema.org sameAs and the footer
export const PROFILES = {
  // Add real URLs as you create each listing
  google: '', // Google Business Profile URL
  yelp: '', // Yelp business page URL
  facebook: '', // Facebook business page URL
  instagram: '', // Instagram profile URL
  linkedin: '', // LinkedIn company page URL
  bbb: '', // BBB listing URL
  angi: '', // Angi/HomeAdvisor listing URL
  thumbtack: '', // Thumbtack profile URL
  nextdoor: '', // Nextdoor business page URL
  apple: '', // Apple Maps listing URL
};

// Per-location directory URLs — each directory listing should link back to the specific location page
// When registering on Yelp/Angi/Google for a specific city, set the website URL to:
//   choosetrue.com/locations/{slug}
// Example: Yelp NYC listing → website: choosetrue.com/locations/new-york-city
// Example: Google Business (Elizabeth) → website: choosetrue.com/locations/elizabeth-nj

// Hub locations shown in footer (not every sub-city)
export const HUB_LOCATIONS = ['elizabeth-nj', 'new-york-city', 'stamford-ct', 'atlanta'];

// Ventilation-specific city landing pages (50-mile radius from Elizabeth NJ)
export const VENTILATION_CITIES = [
  // NJ Cities
  {
    slug: 'elizabeth-nj',
    city: 'Elizabeth',
    state: 'NJ',
    region: 'Union County',
    restaurantScene: 'Elizabeth has over 1,200 restaurants and food establishments — from the diverse Latin and Portuguese eateries along Elizabeth Avenue to the commercial kitchens serving Newark Airport hotels. Every one of them runs an exhaust hood that needs proper air balancing.',
    neighborhoods: ['Elmora', 'Midtown', 'Bayway', 'Elizabeth Port', 'Westminster'],
    nearbyAreas: ['Linden', 'Roselle', 'Rahway', 'Clark', 'Hillside', 'Union'],
  },
  {
    slug: 'newark-nj',
    city: 'Newark',
    state: 'NJ',
    region: 'Essex County',
    restaurantScene: 'The Ironbound district alone has hundreds of restaurants — Portuguese, Spanish, Brazilian, and more — all running commercial kitchen hoods that need balancing. Add Downtown Newark\'s growing food scene and Newark Airport\'s hotel kitchens, and the demand is massive.',
    neighborhoods: ['Ironbound', 'Downtown', 'North Newark', 'Vailsburg', 'Roseville'],
    nearbyAreas: ['East Orange', 'Irvington', 'Belleville', 'Bloomfield', 'Nutley', 'Montclair'],
  },
  {
    slug: 'jersey-city-nj',
    city: 'Jersey City',
    state: 'NJ',
    region: 'Hudson County',
    restaurantScene: 'Jersey City is one of the fastest-growing restaurant markets on the East Coast. From the waterfront restaurants in Downtown JC to the Indian restaurants along Newark Avenue, the brunch spots on Grove Street, and the food halls in Journal Square — the kitchen ventilation demand is exploding.',
    neighborhoods: ['Downtown', 'Journal Square', 'Heights', 'Greenville', 'Bergen-Lafayette'],
    nearbyAreas: ['Hoboken', 'Union City', 'North Bergen', 'Bayonne', 'Weehawken', 'Secaucus'],
  },
  {
    slug: 'paterson-nj',
    city: 'Paterson',
    state: 'NJ',
    region: 'Passaic County',
    restaurantScene: 'Paterson\'s vibrant food scene is anchored by Main Street\'s Middle Eastern bakeries and restaurants, plus Latin eateries throughout the city. These kitchens run hard — high-heat cooking, heavy grease loads, and exhaust systems that need expert balancing.',
    neighborhoods: ['Main Street District', 'South Paterson', 'Eastside', 'Northside'],
    nearbyAreas: ['Clifton', 'Passaic', 'Wayne', 'Totowa', 'Fair Lawn', 'Hawthorne'],
  },
  {
    slug: 'new-brunswick-nj',
    city: 'New Brunswick',
    state: 'NJ',
    region: 'Middlesex County',
    restaurantScene: 'New Brunswick\'s George Street restaurant row, the Rutgers campus dining halls, and the growing food scene along Route 1 all rely on commercial kitchen ventilation. University dining alone represents dozens of hood systems that need regular balancing.',
    neighborhoods: ['Downtown', 'George Street', 'Route 1 Corridor', 'French Street'],
    nearbyAreas: ['Edison', 'Piscataway', 'Highland Park', 'Woodbridge', 'Perth Amboy', 'Metuchen'],
  },
  {
    slug: 'morristown-nj',
    city: 'Morristown',
    state: 'NJ',
    region: 'Morris County',
    restaurantScene: 'Morristown\'s Green and surrounding streets have become a dining destination — upscale restaurants, gastropubs, and cafes filling historic buildings. Morris County\'s corporate campuses add institutional cafeterias and executive dining rooms to the mix.',
    neighborhoods: ['The Green', 'South Street', 'Speedwell Avenue'],
    nearbyAreas: ['Parsippany', 'Morris Plains', 'Madison', 'Florham Park', 'East Hanover', 'Denville'],
  },
  {
    slug: 'woodbridge-nj',
    city: 'Woodbridge',
    state: 'NJ',
    region: 'Middlesex County',
    restaurantScene: 'Woodbridge Township sits at the crossroads of the NJ Turnpike and Garden State Parkway — surrounded by restaurants, hotels, and commercial kitchens serving one of the most densely populated areas in the country. Route 1 and Route 9 corridors are lined with dining establishments.',
    neighborhoods: ['Woodbridge Proper', 'Iselin', 'Avenel', 'Colonia', 'Port Reading'],
    nearbyAreas: ['Edison', 'Rahway', 'Carteret', 'Perth Amboy', 'Linden', 'Clark'],
  },
  // NYC Boroughs
  {
    slug: 'manhattan-ny',
    city: 'Manhattan',
    state: 'NY',
    region: 'New York City',
    restaurantScene: 'Manhattan has over 10,000 restaurants — the highest concentration in the world. From Michelin-starred kitchens in Tribeca to the pizza shops of Hell\'s Kitchen, dim sum in Chinatown to steakhouses in Midtown. Every one runs an exhaust hood. Most have never been properly balanced.',
    neighborhoods: ['Midtown', 'Lower Manhattan', 'Upper East Side', 'Chelsea', 'SoHo', 'Tribeca', 'Harlem', 'Hell\'s Kitchen', 'Chinatown', 'East Village'],
    nearbyAreas: ['Brooklyn', 'Queens', 'Jersey City', 'Hoboken'],
  },
  {
    slug: 'brooklyn-ny',
    city: 'Brooklyn',
    state: 'NY',
    region: 'New York City',
    restaurantScene: 'Brooklyn\'s food scene is legendary — from the craft cocktail bars of Williamsburg to the taquerias of Sunset Park, the Russian restaurants of Brighton Beach to the West Indian eateries of Flatbush. Over 5,000 restaurants and growing. Kitchen ventilation demand is enormous.',
    neighborhoods: ['Williamsburg', 'DUMBO', 'Park Slope', 'Bushwick', 'Crown Heights', 'Bay Ridge', 'Sunset Park', 'Flatbush', 'Greenpoint', 'Red Hook'],
    nearbyAreas: ['Manhattan', 'Queens', 'Staten Island'],
  },
  {
    slug: 'queens-ny',
    city: 'Queens',
    state: 'NY',
    region: 'New York City',
    restaurantScene: 'Queens is the most ethnically diverse county in the US — and the food proves it. Greek tavernas in Astoria, dim sum palaces in Flushing, Colombian bakeries in Jackson Heights, Indian restaurants on Hillside Avenue. These kitchens cook hard and their ventilation systems need expert service.',
    neighborhoods: ['Astoria', 'Flushing', 'Jackson Heights', 'Long Island City', 'Jamaica', 'Forest Hills', 'Elmhurst', 'Bayside', 'Ridgewood', 'Corona'],
    nearbyAreas: ['Manhattan', 'Brooklyn', 'The Bronx', 'Long Island'],
  },
  {
    slug: 'bronx-ny',
    city: 'The Bronx',
    state: 'NY',
    region: 'New York City',
    restaurantScene: 'From Arthur Avenue\'s legendary Italian restaurants to the Dominican bakeries of Fordham, the seafood spots on City Island to the booming Mott Haven food scene. Plus Hunts Point Market — the largest food distribution center in the world — surrounded by commercial kitchens.',
    neighborhoods: ['Arthur Avenue', 'Fordham', 'Mott Haven', 'City Island', 'Riverdale', 'Pelham Bay', 'Kingsbridge'],
    nearbyAreas: ['Manhattan', 'Queens', 'Westchester'],
  },
  {
    slug: 'staten-island-ny',
    city: 'Staten Island',
    state: 'NY',
    region: 'New York City',
    restaurantScene: 'Staten Island\'s restaurant scene runs along Hylan Boulevard and Forest Avenue — Italian restaurants, pizzerias, diners, and a growing international food presence. Closest NYC borough to our Elizabeth NJ home base, just across the Goethals Bridge.',
    neighborhoods: ['St. George', 'New Dorp', 'Tottenville', 'Great Kills', 'West Brighton', 'Port Richmond'],
    nearbyAreas: ['Elizabeth NJ', 'Brooklyn', 'Bayonne NJ'],
  },
  // CT (edge of 50-mile radius)
  {
    slug: 'stamford-ct',
    city: 'Stamford',
    state: 'CT',
    region: 'Fairfield County',
    restaurantScene: 'Stamford\'s downtown has transformed into a dining hub — restaurants, bars, and hotels along Bedford Street, Atlantic Street, and Harbor Point. Corporate campuses in Stamford and Greenwich add institutional kitchens. Few kitchen ventilation specialists serve this market.',
    neighborhoods: ['Downtown', 'Harbor Point', 'Springdale', 'Glenbrook'],
    nearbyAreas: ['Greenwich', 'Norwalk', 'Darien', 'New Canaan', 'White Plains NY'],
  },
  {
    slug: 'white-plains-ny',
    city: 'White Plains',
    state: 'NY',
    region: 'Westchester County',
    restaurantScene: 'White Plains is the commercial hub of Westchester County — restaurants along Mamaroneck Avenue and Main Street, plus hotel kitchens, hospital cafeterias, and corporate dining facilities. Westchester\'s restaurant density rivals many NYC neighborhoods.',
    neighborhoods: ['Downtown', 'Mamaroneck Avenue', 'Battle Hill'],
    nearbyAreas: ['Yonkers', 'New Rochelle', 'Scarsdale', 'Tarrytown', 'Mount Vernon', 'Port Chester'],
  },
  // CT ventilation cities
  {
    slug: 'norwalk-ct',
    city: 'Norwalk',
    state: 'CT',
    region: 'Fairfield County',
    restaurantScene: 'Norwalk\'s SoNo (South Norwalk) district has become one of Connecticut\'s top dining destinations — restaurants, breweries, and oyster bars packed along Washington and Main Streets. Westport adds upscale dining. All need ventilation service.',
    neighborhoods: ['SoNo', 'East Norwalk', 'Rowayton', 'Cranbury'],
    nearbyAreas: ['Westport', 'Weston', 'Wilton', 'Darien', 'Stamford', 'Ridgefield'],
  },
  {
    slug: 'bridgeport-ct',
    city: 'Bridgeport',
    state: 'CT',
    region: 'Fairfield County',
    restaurantScene: 'Bridgeport is Connecticut\'s largest city with a diverse food scene — from downtown restaurants to the institutional kitchens at Bridgeport Hospital, Sacred Heart University, and the Webster Bank Arena. The Black Rock neighborhood has an emerging restaurant row.',
    neighborhoods: ['Downtown', 'Black Rock', 'North End', 'East Side'],
    nearbyAreas: ['Trumbull', 'Stratford', 'Shelton', 'Milford', 'Fairfield', 'Monroe'],
  },
  {
    slug: 'new-haven-ct',
    city: 'New Haven',
    state: 'CT',
    region: 'New Haven County',
    restaurantScene: 'New Haven is a food city — legendary pizza on Wooster Street (Frank Pepe\'s, Sally\'s, Modern), Yale University\'s massive dining operations, and a thriving restaurant scene from Chapel Street to the Westville neighborhood. Kitchen ventilation demand is strong and underserved.',
    neighborhoods: ['Wooster Square', 'Downtown', 'Chapel District', 'East Rock', 'Westville'],
    nearbyAreas: ['West Haven', 'East Haven', 'Hamden', 'North Haven', 'Branford', 'Guilford'],
  },
];

export const STATS = [
  { value: '4hr', label: 'Average Response Time' },
  { value: '94%', label: 'First-Time Fix Rate' },
  { value: '24/7', label: 'Emergency Service' },
  { value: '90-Day', label: 'Parts & Labor Guarantee' },
];

export const MANUFACTURERS = [
  'Rational', 'Hoshizaki', 'True Manufacturing', 'Alto-Shaam',
  'Vulcan', 'Traulsen', 'Manitowoc', 'Blodgett',
  'La Marzocco', 'Carrier', 'Turbo Air', 'Scotsman',
  'Garland', 'Pitco', 'Delfield', 'Bunn',
];

export const TESTIMONIALS = [
  {
    quote: 'True Commercial showed up same day, diagnosed the issue in 20 minutes, and had our combi oven running before dinner service. Nobody else even called us back.',
    author: 'Michael R.',
    role: 'Executive Chef',
    location: 'Elizabeth, NJ',
  },
  {
    quote: 'We switched from a national provider to True and the difference is night and day. Actual humans who know our equipment and show up when they say they will.',
    author: 'Sarah K.',
    role: 'Director of Operations',
    location: 'Newark, NJ',
  },
  {
    quote: 'The PM program has already paid for itself. We haven\'t had an emergency call in six months. That\'s unheard of for a kitchen our size.',
    author: 'David T.',
    role: 'Facilities Manager',
    location: 'Jersey City, NJ',
  },
];
