export const COMPANY = {
  name: 'True Commercial Service',
  legal: 'True Commercial Service LLC',
  phone: '(405) 555-8247',
  phoneHref: 'tel:+14055558247',
  emergencyPhone: '(405) 555-8248',
  emergencyPhoneHref: 'tel:+14055558248',
  email: 'service@choosetrue.com',
  tagline: 'Commercial Kitchen Equipment Repair. Done Right.',
  description: 'True Commercial Service is a tech-forward commercial kitchen equipment repair company serving Oklahoma City, Northern New Jersey, and Atlanta.',
};

export const SERVICES = [
  {
    slug: 'cooking-equipment',
    title: 'Cooking Equipment Repair',
    shortTitle: 'Cooking',
    icon: 'Flame',
    description: 'Ovens, ranges, fryers, griddles, steamers, and more. Factory-trained techs who fix it right the first time.',
    longDescription: 'From combi ovens to conveyor ovens, charbroilers to tilt skillets — we repair every major brand of commercial cooking equipment. Our technicians carry manufacturer certifications and the diagnostic tools to identify issues fast. No guesswork. No repeat visits.',
    equipment: ['Combi Ovens', 'Convection Ovens', 'Conveyor Ovens', 'Fryers', 'Griddles', 'Charbroilers', 'Ranges', 'Steamers', 'Tilt Skillets', 'Salamanders', 'Rotisseries', 'Induction Cooktops'],
    brands: ['Rational', 'Alto-Shaam', 'Vulcan', 'Garland', 'Blodgett', 'Henny Penny', 'Pitco', 'Frymaster', 'Cleveland', 'TurboChef'],
  },
  {
    slug: 'refrigeration',
    title: 'Commercial Refrigeration Repair',
    shortTitle: 'Refrigeration',
    icon: 'Thermometer',
    description: 'Walk-in coolers, reach-ins, prep tables, display cases. Fast response to protect your inventory.',
    longDescription: 'Refrigeration failures cost you money every minute. We prioritize refrigeration calls because your inventory is on the line. Walk-in coolers, reach-in units, prep tables, display merchandisers — we service them all with the urgency they demand.',
    equipment: ['Walk-In Coolers', 'Walk-In Freezers', 'Reach-In Refrigerators', 'Prep Tables', 'Display Cases', 'Ice Cream Cabinets', 'Blast Chillers', 'Undercounter Units', 'Refrigerated Bases'],
    brands: ['True Manufacturing', 'Traulsen', 'Hoshizaki', 'Turbo Air', 'Continental', 'Beverage-Air', 'Delfield', 'Randell', 'Master-Bilt'],
  },
  {
    slug: 'hvac',
    title: 'Commercial HVAC Service',
    shortTitle: 'HVAC',
    icon: 'Wind',
    description: 'Rooftop units, kitchen ventilation, makeup air. Keep your kitchen and dining room comfortable year-round.',
    longDescription: 'Commercial kitchens generate massive amounts of heat. Your HVAC system is working harder than anywhere else. We maintain and repair rooftop units, split systems, kitchen ventilation hoods, makeup air units, and exhaust fans — keeping your staff comfortable and your kitchen code-compliant.',
    equipment: ['Rooftop Units (RTUs)', 'Split Systems', 'Kitchen Exhaust Hoods', 'Makeup Air Units', 'Exhaust Fans', 'VRF Systems', 'Walk-In Unit Coolers', 'Condensing Units'],
    brands: ['Carrier', 'Trane', 'Lennox', 'Daikin', 'Bard', 'Captive Aire', 'Accurex'],
  },
  {
    slug: 'beverage-equipment',
    title: 'Beverage Equipment Repair',
    shortTitle: 'Beverage',
    icon: 'GlassWater',
    description: 'Ice machines, fountain dispensers, tea brewers, juice systems. Keep the drinks flowing.',
    longDescription: 'Nothing slows down service like a broken ice machine or a downed fountain system. We repair and maintain all major brands of commercial beverage equipment — from Hoshizaki and Manitowoc ice machines to Bunn brewers and fountain systems.',
    equipment: ['Ice Machines', 'Fountain Dispensers', 'Tea Brewers', 'Coffee Brewers', 'Juice Dispensers', 'Beer Systems', 'Water Filtration', 'Carbonation Systems'],
    brands: ['Hoshizaki', 'Manitowoc', 'Scotsman', 'Ice-O-Matic', 'Bunn', 'Cornelius', 'Lancer', 'Wunder-Bar'],
  },
  {
    slug: 'espresso-machines',
    title: 'Espresso Machine Repair',
    shortTitle: 'Espresso',
    icon: 'Coffee',
    description: 'Specialized service for commercial espresso machines. Multi-group, superautomatic, and grinders.',
    longDescription: 'Commercial espresso machines are precision instruments. Most service companies won\'t touch them. We will — and we\'ll fix them right. From PID tuning to group head rebuilds, boiler descaling to grinder calibration, our techs have deep training on the machines that matter to your coffee program.',
    equipment: ['Multi-Group Espresso Machines', 'Superautomatic Machines', 'Commercial Grinders', 'Steam Wands', 'Group Heads', 'Boilers', 'Water Treatment Systems'],
    brands: ['La Marzocco', 'Nuova Simonelli', 'La Cimbali', 'Rancilio', 'Slayer', 'Synesso', 'Mazzer', 'Mahlkönig'],
  },
  {
    slug: 'preventive-maintenance',
    title: 'Preventive Maintenance Agreements',
    shortTitle: 'PM Plans',
    icon: 'ShieldCheck',
    description: 'Scheduled maintenance that extends equipment life and prevents costly emergency calls.',
    longDescription: 'The smartest operators don\'t wait for breakdowns. Our Preventive Maintenance agreements put your equipment on a scheduled service cadence — cleaning, calibrating, and inspecting before small issues become expensive emergencies. We build custom PM plans based on your equipment inventory and usage patterns.',
    equipment: ['Full Kitchen PM Programs', 'Refrigeration-Only PM', 'HVAC PM', 'Custom Equipment Audits', 'Seasonal Tune-Ups'],
    brands: [],
  },
];

export const LOCATIONS = [
  {
    slug: 'oklahoma-city',
    city: 'Oklahoma City',
    state: 'OK',
    status: 'active' as const,
    tagline: 'Serving the OKC Metro and Central Oklahoma',
    phone: '(405) 555-8247',
    phoneHref: 'tel:+14055558247',
    serviceArea: ['Oklahoma City', 'Norman', 'Edmond', 'Moore', 'Midwest City', 'Del City', 'Yukon', 'Mustang', 'Bethany', 'Stillwater', 'Shawnee'],
    description: 'True Commercial Service is Oklahoma City\'s premier commercial kitchen equipment repair provider. From Bricktown restaurants to campus dining at OU and OSU, we keep commercial kitchens running across Central Oklahoma.',
    seoTitle: 'Oklahoma City Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Expert commercial kitchen equipment repair in Oklahoma City. Cooking, refrigeration, HVAC, and espresso machine service for restaurants, schools, and institutions across the OKC metro.',
    seoKeyword: 'Oklahoma City commercial kitchen equipment repair',
  },
  {
    slug: 'elizabeth-nj',
    city: 'Northern NJ / NYC',
    state: 'NJ',
    status: 'coming-soon' as const,
    tagline: 'Serving Northern New Jersey and the NYC Metro',
    phone: '(908) 555-8247',
    phoneHref: 'tel:+19085558247',
    serviceArea: ['Elizabeth', 'Newark', 'Jersey City', 'Hoboken', 'Paterson', 'Clifton', 'Passaic', 'Union City', 'Bayonne', 'New Brunswick'],
    description: 'True Commercial Service is bringing tech-forward commercial kitchen equipment repair to the Northern New Jersey and NYC metro area. From Elizabeth to Newark to Jersey City, we\'re building the service operation the Tri-State area deserves.',
    seoTitle: 'Northern NJ Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair coming to Northern New Jersey and NYC metro. Cooking, refrigeration, HVAC service for restaurants, hotels, and institutions.',
    seoKeyword: 'New Jersey commercial kitchen equipment repair',
  },
  {
    slug: 'atlanta',
    city: 'Atlanta',
    state: 'GA',
    status: 'coming-soon' as const,
    tagline: 'Serving Metro Atlanta and North Georgia',
    phone: '(470) 555-8247',
    phoneHref: 'tel:+14705558247',
    serviceArea: ['Atlanta', 'Marietta', 'Decatur', 'Sandy Springs', 'Roswell', 'Alpharetta', 'Kennesaw', 'Smyrna', 'Duluth', 'Lawrenceville'],
    description: 'True Commercial Service is expanding to Atlanta — bringing our tech-forward approach to commercial kitchen equipment repair across Metro Atlanta and North Georgia.',
    seoTitle: 'Atlanta Commercial Kitchen Equipment Repair | True Commercial Service',
    seoDescription: 'Commercial kitchen equipment repair coming to Metro Atlanta. Expert cooking, refrigeration, HVAC service for restaurants, grocery stores, and institutions.',
    seoKeyword: 'Atlanta commercial kitchen equipment repair',
  },
];

export const VERTICALS = [
  {
    slug: 'restaurants',
    title: 'Restaurants',
    icon: 'UtensilsCrossed',
    description: 'From fast casual to fine dining. We know the urgency of a kitchen going down during service.',
    longDescription: 'A broken fryer at 5pm on a Friday isn\'t a maintenance issue — it\'s a revenue emergency. We get that. True Commercial Service is built around the reality of restaurant operations: tight margins, high volume, and zero tolerance for downtime. Our response times, diagnostic speed, and first-time fix rates reflect that urgency.',
    painPoints: ['Equipment failures during peak hours', 'Inconsistent service from rotating techs', 'Long wait times for parts', 'Lack of manufacturer expertise'],
  },
  {
    slug: 'grocery-stores',
    title: 'Grocery Stores',
    icon: 'ShoppingCart',
    description: 'Refrigeration-critical environments with zero tolerance for temperature excursions.',
    longDescription: 'When your walk-in goes down, you\'re not just losing equipment uptime — you\'re losing inventory. Grocery and convenience store operators need a service partner who understands refrigeration urgency, health code compliance, and the specific demands of high-volume retail food environments.',
    painPoints: ['Perishable inventory at risk', 'Multi-unit consistency', 'Health department compliance', 'After-hours emergency needs'],
  },
  {
    slug: 'schools-institutions',
    title: 'Schools & Institutions',
    icon: 'GraduationCap',
    description: 'University dining, K-12 cafeterias, hospital kitchens, and government facilities.',
    longDescription: 'Institutional foodservice operates on fixed budgets with non-negotiable feeding schedules. When equipment goes down at a school cafeteria or hospital kitchen, there\'s no backup plan. We work with institutional operators to build PM programs that prevent emergencies and respond fast when they happen.',
    painPoints: ['Fixed feeding schedules', 'Budget constraints', 'Procurement processes', 'Code and compliance requirements'],
  },
  {
    slug: 'hotels',
    title: 'Hotels & Hospitality',
    icon: 'Building2',
    description: 'Full-service hotel kitchens, banquet facilities, room service operations.',
    longDescription: 'Hotel foodservice is complex — multiple outlets, banquet operations, room service, and often a coffee program that\'s the first touchpoint for every guest. We support hotel engineering teams with responsive service that understands the hospitality standard.',
    painPoints: ['Multiple foodservice outlets', 'Guest-facing quality standards', 'Banquet and event deadlines', '24/7 operational demands'],
  },
];

export const STATS = [
  { value: '4hr', label: 'Average Response Time' },
  { value: '94%', label: 'First-Time Fix Rate' },
  { value: '24/7', label: 'Emergency Service' },
  { value: '90-Day', label: 'Parts & Labor Guarantee' },
];

export const MANUFACTURERS = [
  'Rational', 'Hoshizaki', 'True Manufacturing', 'Alto-Shaam',
  'Vulcan', 'Traulsen', 'Manitowoc', 'Blodgett',
  'La Marzocco', 'Carrier', 'Turbo Air', 'Scotsman',
  'Garland', 'Pitco', 'Delfield', 'Bunn',
];

export const TESTIMONIALS = [
  {
    quote: 'True Commercial showed up same day, diagnosed the issue in 20 minutes, and had our combi oven running before dinner service. Nobody else even called us back.',
    author: 'Michael R.',
    role: 'Executive Chef',
    location: 'Oklahoma City, OK',
  },
  {
    quote: 'We switched from a national provider to True and the difference is night and day. Actual humans who know our equipment and show up when they say they will.',
    author: 'Sarah K.',
    role: 'Director of Operations',
    location: 'Norman, OK',
  },
  {
    quote: 'The PM program has already paid for itself. We haven\'t had an emergency call in six months. That\'s unheard of for a kitchen our size.',
    author: 'David T.',
    role: 'Facilities Manager',
    location: 'Edmond, OK',
  },
];
